app = "repo-misty-sound-8256"
primary_region = "lhr"

[build]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[processes]]
  type = "app"
  command = "python /app/main.py"